=== 2026.06-pre1

==== utils-rest-server-connector

===== Dependency Updates

* Upgraded to Spring Boot 4.0.1
* Upgraded to Spring Framework 7.0.2
* Upgraded to Jackson 2.21.0
* Supports Java 25
* Replaced OkHttp with Apache HttpClient 5 (`org.apache.httpcomponents.client5:httpclient5`)

===== Breaking Changes


====== HttpClient

* Replaced `OkHttpClient` with Apache `HttpClient` from `org.apache.hc.client5.http.classic.HttpClient` with default implementation `CloseableHttpClient`
** Default configurations:
*** Using `PoolingHttpClientConnectionManager` as connection manager
*** Most of the timeouts (connection, socket, connection request) are set to 5 minutes instead of infinite as previously with OkHttpClient

* `RestServerConnectorFactoryBuilder.withHttpClient()` now accepts `HttpClient` instead of `OkHttpClient`

====== RestTemplate to RestClient

* `RestTemplate` usage has been replaced with `RestClient` (Spring Framework 7 preferred API)

====== ResponseErrorHandler

* Spring Framework 7 removed `org.springframework.web.client.ResponseErrorHandler` interface
* A new `com.mgmtp.a12.connector.rest.ResponseErrorHandler` interface is introduced to continue supporting global error handling
** `hasError(HttpStatusCode httpStatusCode)`: indicates whether the given response status is an error
** `handleError(HttpRequest request, ClientHttpResponse response)`: handles the error response if `hasError` returned true
